# 
# Translators:
# Arturo Lorenzo <shroomeater@gmail.com>, 2025
# Andres Henriquez, 2025
# 
msgid ""
msgstr ""
"Project-Id-Version: Lizmap Web Client 3.9 dataviz\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-03-06 09:49++0000\n"
"PO-Revision-Date: 2025-01-24 10:32+0000\n"
"Last-Translator: Andres Henriquez, 2025\n"
"Language-Team: Spanish (https://app.transifex.com/3liz-1/teams/62012/es/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: es\n"
"Plural-Forms: nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;\n"

#: dataviz~dataviz.dock.subtitle
msgctxt "dataviz~dataviz.dock.subtitle"
msgid "Dataviz"
msgstr "Visualización de datos"

#: dataviz~dataviz.dock.title
msgctxt "dataviz~dataviz.dock.title"
msgid "Dataviz"
msgstr "Visualización de datos"

#: dataviz~dataviz.log.access_denied.detail
msgctxt "dataviz~dataviz.log.access_denied.detail"
msgid ""
"You have no right to access this ressource. Have you used the right login ?"
msgstr ""
"No tiene permisos para acceder a este recurso.\n"
"¿Ha ingresado con el usuario correcto?"

#: dataviz~dataviz.log.access_denied.title
msgctxt "dataviz~dataviz.log.access_denied.title"
msgid "Access denied"
msgstr "Acceso rechazado"

#: dataviz~dataviz.log.invalid_plot_type.detail
msgctxt "dataviz~dataviz.log.invalid_plot_type.detail"
msgid "The given plot type \"%s\" is invalid."
msgstr ""

#: dataviz~dataviz.log.invalid_plot_type.title
msgctxt "dataviz~dataviz.log.invalid_plot_type.title"
msgid "Invalid plot type"
msgstr ""

#: dataviz~dataviz.log.layer_not_found.detail
msgctxt "dataviz~dataviz.log.layer_not_found.detail"
msgid ""
"The layer with the given ID \"%s\" cannot be found in the published QGIS "
"project."
msgstr "La capa con el ID \"%s\" no se ha sido encontrada en el proyecto de QGIS."

#: dataviz~dataviz.log.layer_not_found.title
msgctxt "dataviz~dataviz.log.layer_not_found.title"
msgid "Layer not found"
msgstr "Capa no encontrada"

#: dataviz~dataviz.log.no_configuration.title
msgctxt "dataviz~dataviz.log.no_configuration.title"
msgid "There is no dataviz configuration for this project yet."
msgstr ""

#: dataviz~dataviz.log.no_data.detail
msgctxt "dataviz~dataviz.log.no_data.detail"
msgid "The plot source data cannot be fetched from the vector layer \"%s\"."
msgstr ""

#: dataviz~dataviz.log.no_data.title
msgctxt "dataviz~dataviz.log.no_data.title"
msgid "Plot data not available"
msgstr ""

#: dataviz~dataviz.log.no_layers.detail
msgctxt "dataviz~dataviz.log.no_layers.detail"
msgid "The table of layers inside the dataviz configuration is empty."
msgstr ""

#: dataviz~dataviz.log.no_layers.title
msgctxt "dataviz~dataviz.log.no_layers.title"
msgid "Dataviz layers is empty"
msgstr ""

#: dataviz~dataviz.log.plot_configuration_not_found.detail
msgctxt "dataviz~dataviz.log.plot_configuration_not_found.detail"
msgid ""
"The plot configuration cannot be found or parsed by Lizmap dataviz API."
msgstr ""

#: dataviz~dataviz.log.plot_configuration_not_found.title
msgctxt "dataviz~dataviz.log.plot_configuration_not_found.title"
msgid "Plot configuration not found"
msgstr ""

#: dataviz~dataviz.log.project_not_found.detail
msgctxt "dataviz~dataviz.log.project_not_found.detail"
msgid ""
"The QGIS project \"%s.qgs\" does not exist or is not available in the "
"repository \"%s\"."
msgstr ""

#: dataviz~dataviz.log.project_not_found.title
msgctxt "dataviz~dataviz.log.project_not_found.title"
msgid "Lizmap project not found"
msgstr "Proyecto no encontrado"

#: dataviz~dataviz.log.repository_not_found.detail
msgctxt "dataviz~dataviz.log.repository_not_found.detail"
msgid "The Lizmap repository \"%s\" does not exist or is not available."
msgstr "El repositorio \"%s\" no existe o no está disponible."

#: dataviz~dataviz.log.repository_not_found.title
msgctxt "dataviz~dataviz.log.repository_not_found.title"
msgid "Lizmap repository not found"
msgstr "No se encontró el repositorio de Lizmap"

#: dataviz~dataviz.log.request_not_supported.detail
msgctxt "dataviz~dataviz.log.request_not_supported.detail"
msgid "The given request \"%s\" is not supported by Lizmap dataviz API."
msgstr ""

#: dataviz~dataviz.log.request_not_supported.title
msgctxt "dataviz~dataviz.log.request_not_supported.title"
msgid "Request is not supported"
msgstr ""

#: dataviz~dataviz.log.wrong_credentials.detail
msgctxt "dataviz~dataviz.log.wrong_credentials.detail"
msgid "The given login and password are incorrect. Cannot authenticate."
msgstr ""
"El usuario y contraseña ingresados son incorrectos. No es posible iniciar la"
" sesión."

#: dataviz~dataviz.log.wrong_credentials.title
msgctxt "dataviz~dataviz.log.wrong_credentials.title"
msgid "Wrong credentials"
msgstr "Credenciales incorrectas"
